apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix-catalog
  template:
    metadata:
      labels:
        app: netflix-catalog
    spec:
      containers:
        - name: netflix-catalog
          image: mohmmad313/netflix_movie_catalog:0.0.1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-catalog-service
spec:
  selector:
    app: netflix-catalog
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
