apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix-frontend
  template:
    metadata:
      labels:
        app: netflix-frontend
    spec:
      containers:
        - name: netflix-frontend
          image: mohmmad313/netflix_frontend:0.0.6
          ports:
            - containerPort: 3000
          env:
            - name: MOVIE_CATALOG_SERVICE
              value: "http://netflix-catalog-service:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-frontend-service
spec:
  selector:
    app: netflix-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
